import { existsSync, readFileSync } from "node:fs";
import { defineConfig } from "vitest/config";

/** Load .env.e2e (generated by e2e-stack.sh) as a key-value record. */
function loadEnvE2e(): Record<string, string> {
	const path = ".env.e2e";
	if (!existsSync(path)) return {};
	const env: Record<string, string> = {};
	for (const line of readFileSync(path, "utf8").split("\n")) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith("#")) continue;
		const eq = trimmed.indexOf("=");
		if (eq > 0) env[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
	}
	return env;
}

export default defineConfig({
	test: {
		passWithNoTests: true,
		projects: [
			{
				test: {
					name: "unit",
					include: ["apps/*/src/**/*.test.ts", "packages/*/src/**/*.test.ts"],
					exclude: ["**/*.db.test.ts"],
				},
			},
			{
				test: {
					name: "db",
					include: ["apps/*/src/**/*.db.test.ts"],
				},
			},
			{
				test: {
					name: "integration",
					root: "tests/integration",
					include: ["**/*.test.ts"],
				},
			},
			{
				test: {
					name: "onchain",
					root: "tests/onchain",
					include: ["**/*.test.ts"],
					testTimeout: 60_000,
				},
			},
			{
				test: {
					name: "e2e",
					root: "tests/e2e",
					include: ["**/*.test.ts"],
					testTimeout: 120_000,
					hookTimeout: 60_000,
					env: loadEnvE2e(),
				},
			},
		],
	},
});
