#!/bin/bash
# Convenience wrapper for the full-stack e2e Docker Compose setup.
#
# Uses two compose files: the offline-mode base stack + our e2e overlay
# that adds the BYOS service and overrides driver/autopilot config.
#
# On "up", the script re-bakes the BYOS contracts into the Anvil state
# and writes contract addresses to .env.e2e so that docker-compose and
# the test helpers can read them without hardcoding.
#
# Usage:
#   ./scripts/e2e-stack.sh up -d --build --wait
#   ./scripts/e2e-stack.sh down -v
#   ./scripts/e2e-stack.sh logs byos-ts
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env.e2e"

# The offline-mode compose references env_file: .env in several services.
# Create it from the example if it doesn't exist.
if [ ! -f "$REPO_ROOT/offline-mode/.env" ]; then
  cp "$REPO_ROOT/offline-mode/.env.example" "$REPO_ROOT/offline-mode/.env"
fi

# Initialize the services submodule if needed (required for Rust builds + Flyway migrations).
if [ ! -f "$REPO_ROOT/offline-mode/modules/services/Cargo.toml" ]; then
  echo "Initializing offline-mode/modules/services submodule..."
  git -C "$REPO_ROOT/offline-mode" submodule update --init modules/services
fi

# Only the services needed for e2e tests. Excludes frontend, explorer,
# grafana, prometheus, tempo, adminer, watch-tower which need additional
# submodules or are not relevant.
E2E_SERVICES=(
  chain-deployer
  chain
  db
  db-migrations
  coingecko-mock
  orderbook
  autopilot
  driver
  baseline
  byos-db
  byos-redis
  byos-ts
  admin
)

PROJECT_NAME="byos-e2e"

compose() {
  docker compose \
    -p "$PROJECT_NAME" \
    -f "$REPO_ROOT/offline-mode/docker-compose.yml" \
    -f "$REPO_ROOT/docker-compose.e2e.yml" \
    "$@"
}

# Re-bake the BYOS contracts into the Anvil state and write addresses
# to .env.e2e. Requires anvil + cast (install via foundryup).
bake_byos_contracts() {
  echo "Baking BYOS contracts into Anvil state..."
  local output
  output=$("$REPO_ROOT/offline-mode/scripts/byos/deploy-byos-contracts.sh" 2>&1)
  echo "$output"

  # Parse addresses and keys from the deploy script output
  local escrow trampoline_factory operator_private_key
  escrow=$(echo "$output" | grep "^Escrow:" | tail -1 | awk '{print $2}')
  trampoline_factory=$(echo "$output" | grep "^TrampolineFactory:" | tail -1 | awk '{print $2}')
  operator_private_key=$(echo "$output" | grep "^OperatorPrivateKey:" | tail -1 | awk '{print $2}')

  if [ -z "$escrow" ] || [ -z "$trampoline_factory" ] || [ -z "$operator_private_key" ]; then
    echo "Error: could not parse contract addresses from deploy output"
    exit 1
  fi

  # Write .env.e2e for docker-compose and test helpers
  cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by e2e-stack.sh — do not edit.
# These addresses come from the baked Anvil state.
ESCROW_ADDRESS=$escrow
TRAMPOLINE_FACTORY=$trampoline_factory
OPERATOR_PRIVATE_KEY=$operator_private_key
ENVEOF

  echo ""
  echo "Wrote $ENV_FILE"
}

# If the command is "up", bake contracts first, then start the stack.
# For other commands (down, logs, ps, etc.), pass through as-is.
if [ "${1:-}" = "up" ]; then
  bake_byos_contracts

  # db-migrations is a one-shot Flyway container that exits after running.
  # --wait treats any exited container (even exit 0) as a failure, so we
  # tolerate that specific case.
  compose "$@" "${E2E_SERVICES[@]}" || {
    if docker inspect "${PROJECT_NAME}-db-migrations-1" --format='{{.State.ExitCode}}' 2>/dev/null | grep -q '^0$'; then
      exit 0
    fi
    exit 1
  }
else
  compose "$@"
fi
